### ISSUE TITLE
About paper

### ISSUE THREAD

**Issue by yangcedrus** [m-pektas/EHGAN#1]
Hello, is there a public version of the paper corresponding to this library now? I didn't find it on Arxiv or Google Scholar.

**Comment by m-pektas** [comment]
Hello, thanks for your interest. Unfortunately, there is no public version yet. When the paper is published, I gonna add an access link to this issue.

**Comment by yangcedrus** [comment]
OK, thanks for your reply.

**Comment by m-pektas** [comment]
@yangcedrus You can access the preprint version of the paper using the following link:

 https://arxiv.org/abs/2210.12524.
